receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
     endpoint: 0.0.0.0:8889
  # clickhouse:
  #   endpoint: http://clickhouse.lontra.shop
  #   username: test_user
  #   password: test_password
  #   database: otel
  #   ttl: 72h
  #   logs_table_name: otel_logs
  #   traces_table_name: otel_traces
  #   metrics_table_name: otel_metrics
  #   timeout: 5s
  #   retry_on_failure:
  #     enabled: true
  #     initial_interval: 5s
  #     max_interval: 30s
  #     max_elapsed_time: 300s
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
      #exporters: [clickhouse]

    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
      #exporters: [clickhouse]

    logs:
      receivers: [otlp]
      exporters: [debug]
      #exporters: [clickhouse]

