version: '2.3'
services:
  otelcol:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol
    restart: always
    networks:
      - test_bridge
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"    

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - test_bridge

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    networks:
      - test_bridge
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"
      - "9411:9411"
    expose:
      - "4317"
      - "4318"

networks:
  test_bridge:
    driver: bridge
