version: '2.3'
services:
  fluentd:
    image: fluentd:latest
    container_name: fluentd
    restart: always
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./docker_log:/fluentd/log/
    ports:
      - 24224:24224
    networks:
      - test_bridge

  nginx1:
    image: nginx:latest
    container_name: nginx1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on: 
    #   - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd
        tag: "docker.nginx.webserver"
    ports:
      - 80:80
    networks:
      - test_bridge

  nginx2:
    image: nginx:latest
    container_name: nginx2
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on: 
    #   - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd
        tag: "docker.nginx.webserver"
    ports:
      - 8080:80
    networks:
      - test_bridge

networks:
  test_bridge:
    driver: bridge
